### ISSUE TITLE
Privát konstruktor

### ISSUE THREAD

**Issue by Attula15** [BME-MIT-IET/iet-hf-2023-snake_case#29]
Ameddig ez a konstruktor privát, addig nem tud lefordulni a program nekem:
![image](https://github.com/BME-MIT-IET/iet-hf-2023-snake_case/assets/100715516/1b0c17d8-3339-433f-9b96-9544f5947cbb)
![image](https://github.com/BME-MIT-IET/iet-hf-2023-snake_case/assets/100715516/eea82b07-8334-4559-a6ca-ef365b3ddb4f)
Légyszíves ellenőrizd, hogy nálad is így van-e vagy pedig ez csak egy lokális probléma. Ha globális, akkor légyszíves orvosold!

**Comment by cseszkabence** [comment]
Ellenőriztem friss pull-al, hibátlanul lebuildelt és műküdik a program. Valószínűleg lokális probléma lehetett.
